Add output option

diff --git a/ci b/ci
--- a/ci
+++ b/ci
@@ -1,11 +1,36 @@
 #!/bin/bash
 
+print_usage() {
+  echo "Usage: $0 [-o output_folder] FOLDERS_AND_FILES" >&2
+}
+
+#############
+### Flags ###
+#############
+
+output=.
+
+while getopts 'o:' flag; do
+  case "${flag}" in
+    o) output="$OPTARG" ;; # Custom output folder
+    *) print_usage
+       exit 1 ;;
+  esac
+done
+
+shift $(($OPTIND - 1)) # shift to positionnal arguments
+
+
 ############
 ### Args ###
 ############
 
 if [ "$#" -eq 0 ]; then
-  echo "Usage: $0 FOLDERS/FILES" >&2
+  print_usage
+  exit 1
+fi
+if [ ! -d "$output" ]; then
+  echo "$0: $output: Cannot open: No such directory"
   exit 1
 fi
 
@@ -17,11 +42,11 @@ for f in "$@"; do
   # If file, simply cipher and add .gpg file extension
   if [ -f "$f" ]; then
     echo "Ciphering file $f" >&2
-    pv "$f" | gpg -e -o "$(basename "$f").gpg"
+    pv "$f" | gpg -e -o "$output/$(basename "$f").gpg"
   # If folder, tar folder before ciphering and add .tar.gz.gpg file extension
   elif [ -d "$f" ]; then
     echo "Ciphering folder $f" >&2
-    tar cf - "$f" | pv -s $(($(du -sk "$f" | awk '{print $1}') * 1024)) | gzip | gpg -e -o "$(basename "$f").tar.gz.gpg"
+    tar cf - "$f" | pv -s $(($(du -sk "$f" | awk '{print $1}') * 1024)) | gzip | gpg -e -o "$output/$(basename "$f").tar.gz.gpg"
   # In case the file/folder got deleted during ciphering of previous files/folders
   else
     echo "File or Folder Not Found: $f" >&2
